name: Cloudflare-Worker

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Git Clone
        run: git clone https://github.com/1436223139/Cloudflare-IP-api.git

      - name: Build frontend & Install Dependencies
        run: cd Cloudflare-IP-api && npm i

      - name: Run Dependencies
        run: npm run deploy:cloudflare

      - name: Publish
        uses: cloudflare/wrangler-action@3.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
